#include "cccam3_web_interface.h"
#include "cccam3_logger.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>

// --- Página HTML Principal (template minimalista) ---
static const char *WEB_PAGE_HTML =
"<!DOCTYPE html>\n"
"<html lang=\"pt\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>CCcam3 — Dashboard</title>\n"
"<style>\n"
":root {\n"
"  --bg:#0b0f14; --surface:#11161d; --surface2:#161c26; --border:#1f2833;\n"
"  --text:#e6edf3; --muted:#8b95a1; --accent:#4f8cff; --accent2:#2f6fd6;\n"
"  --green:#2ecc71; --amber:#f0b429; --red:#ef5350; --radius:10px;\n"
"}\n"
"* { margin:0; padding:0; box-sizing:border-box; }\n"
"body { font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Inter,sans-serif; background:var(--bg); color:var(--text); font-size:14px; line-height:1.5; -webkit-font-smoothing:antialiased; }\n"
"button { font-family:inherit; }\n"
".topbar { display:flex; align-items:center; gap:24px; padding:14px 28px; background:rgba(17,22,29,0.85); backdrop-filter:blur(8px); border-bottom:1px solid var(--border); position:sticky; top:0; z-index:10; }\n"
".brand { display:flex; align-items:center; gap:12px; }\n"
".logo { width:38px; height:38px; border-radius:9px; background:linear-gradient(135deg,var(--accent),var(--accent2)); display:flex; align-items:center; justify-content:center; font-weight:700; font-size:15px; color:#fff; letter-spacing:0.5px; }\n"
".name { font-weight:600; font-size:15px; }\n"
".sub { font-size:11px; color:var(--muted); }\n"
".status { display:flex; align-items:center; gap:8px; font-size:12px; color:var(--muted); }\n"
".dot { width:8px; height:8px; border-radius:50%; background:var(--red); transition:0.3s; }\n"
".dot.on { background:var(--green); box-shadow:0 0 8px rgba(46,204,113,0.7); }\n"
".sep { opacity:0.4; }\n"
".actions { margin-left:auto; display:flex; align-items:center; gap:8px; }\n"
".last-update { font-size:11px; color:var(--muted); margin-right:6px; }\n"
".btn { border:none; border-radius:8px; padding:8px 14px; font-size:12.5px; cursor:pointer; transition:0.2s; }\n"
".btn.primary { background:var(--accent); color:#fff; }\n"
".btn.primary:hover { background:var(--accent2); }\n"
".btn.ghost { background:transparent; color:var(--muted); border:1px solid var(--border); }\n"
".btn.ghost:hover { color:var(--text); border-color:var(--accent); }\n"
".btn.ghost.paused { color:var(--amber); border-color:var(--amber); }\n"
"main { max-width:1280px; margin:0 auto; padding:24px 28px 40px; }\n"
".kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:14px; margin-bottom:20px; }\n"
".kpi { background:var(--surface); border:1px solid var(--border); border-radius:var(--radius); padding:16px 18px; transition:0.2s; }\n"
".kpi:hover { border-color:#2c3a4a; }\n"
".kpi .label { font-size:11px; text-transform:uppercase; letter-spacing:0.8px; color:var(--muted); margin-bottom:6px; }\n"
".kpi .value { font-size:26px; font-weight:600; font-variant-numeric:tabular-nums; }\n"
".kpi .value.ok { color:var(--green); }\n"
".kpi .value.warn { color:var(--amber); }\n"
".kpi .value.bad { color:var(--red); }\n"
".grid { display:grid; grid-template-columns:1.6fr 1fr; gap:14px; margin-bottom:20px; }\n"
".card { background:var(--surface); border:1px solid var(--border); border-radius:var(--radius); padding:18px 20px; margin-bottom:0; }\n"
".card-head { display:flex; align-items:center; justify-content:space-between; margin-bottom:14px; }\n"
".card-head h2 { font-size:13px; font-weight:600; text-transform:uppercase; letter-spacing:0.8px; color:var(--muted); }\n"
".pill { background:rgba(79,140,255,0.12); color:var(--accent); border-radius:20px; padding:2px 10px; font-size:11.5px; }\n"
"canvas { width:100%; display:block; }\n"
".kv { display:grid; grid-template-columns:1fr 1fr; gap:10px 18px; }\n"
".kv .k { color:var(--muted); font-size:12.5px; }\n"
".kv .v { font-weight:500; font-variant-numeric:tabular-nums; text-align:right; }\n"
"table { width:100%; border-collapse:collapse; font-size:13px; }\n"
"th { text-align:left; padding:9px 12px; color:var(--muted); font-weight:500; font-size:11px; text-transform:uppercase; letter-spacing:0.6px; border-bottom:1px solid var(--border); }\n"
"td { padding:9px 12px; border-bottom:1px solid rgba(31,40,51,0.6); font-variant-numeric:tabular-nums; }\n"
"tr:last-child td { border-bottom:none; }\n"
"tbody tr { transition:background 0.15s; }\n"
"tbody tr:hover { background:rgba(255,255,255,0.02); }\n"
".badge { display:inline-block; padding:2px 10px; border-radius:20px; font-size:11px; font-weight:500; }\n"
".badge.ok { background:rgba(46,204,113,0.12); color:var(--green); }\n"
".badge.err { background:rgba(239,83,80,0.12); color:var(--red); }\n"
".badge.idle { background:rgba(139,149,161,0.12); color:var(--muted); }\n"
".kick { background:transparent; border:1px solid rgba(239,83,80,0.4); color:var(--red); border-radius:6px; padding:3px 10px; font-size:11.5px; cursor:pointer; transition:0.2s; }\n"
".kick:hover { background:var(--red); color:#fff; }\n"
".bars { display:flex; flex-direction:column; gap:10px; }\n"
".bar-row { display:grid; grid-template-columns:110px 1fr 40px; align-items:center; gap:10px; font-size:12.5px; }\n"
".bar-row .l { color:var(--muted); }\n"
".bar-track { height:7px; background:var(--surface2); border-radius:6px; overflow:hidden; }\n"
".bar-fill { height:100%; background:linear-gradient(90deg,var(--accent2),var(--accent)); border-radius:6px; transition:width 0.6s ease; }\n"
".bar-row .n { text-align:right; font-variant-numeric:tabular-nums; color:var(--muted); }\n"
".empty { text-align:center; color:var(--muted); padding:22px 0; font-size:12.5px; }\n"
"footer { text-align:center; color:#3d4854; font-size:11.5px; padding:18px; border-top:1px solid var(--border); }\n"
"#toast { position:fixed; bottom:24px; right:24px; background:var(--surface2); border:1px solid var(--border); border-radius:10px; padding:12px 18px; font-size:13px; opacity:0; transform:translateY(10px); transition:0.25s; pointer-events:none; z-index:20; }\n"
"#toast.show { opacity:1; transform:translateY(0); }\n"
"#toast.ok { border-color:rgba(46,204,113,0.5); }\n"
"#toast.err { border-color:rgba(239,83,80,0.5); }\n"
"@media (max-width:900px) { .grid { grid-template-columns:1fr; } .topbar { flex-wrap:wrap; } }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header class=\"topbar\">\n"
"  <div class=\"brand\"><div class=\"logo\">C3</div><div><div class=\"name\">CCcam3</div><div class=\"sub\">Servidor de partilha</div></div></div>\n"
"  <div class=\"status\"><span class=\"dot\" id=\"dot\"></span><span id=\"statusText\">a ligar…</span><span class=\"sep\">·</span><span id=\"uptime\"></span></div>\n"
"  <div class=\"actions\">\n"
"    <span class=\"last-update\" id=\"lastUpdate\"></span>\n"
"    <button class=\"btn ghost\" id=\"btnPause\">⏸ Pausar</button>\n"
"    <button class=\"btn ghost\" id=\"btnKeys\">Recarregar chaves</button>\n"
"    <button class=\"btn primary\" id=\"btnRefresh\">↻ Atualizar</button>\n"
"  </div>\n"
"</header>\n"
"<main>\n"
"  <section class=\"kpis\">\n"
"    <div class=\"kpi\"><div class=\"label\">Clientes</div><div class=\"value\" id=\"kClients\">—</div></div>\n"
"    <div class=\"kpi\"><div class=\"label\">Cache</div><div class=\"value\" id=\"kCache\">—</div></div>\n"
"    <div class=\"kpi\"><div class=\"label\">Hit ratio</div><div class=\"value ok\" id=\"kRatio\">—</div></div>\n"
"    <div class=\"kpi\"><div class=\"label\">ECMs / min</div><div class=\"value\" id=\"kEcmRate\">—</div></div>\n"
"    <div class=\"kpi\"><div class=\"label\">Leitor sucesso</div><div class=\"value ok\" id=\"kSucesso\">—</div></div>\n"
"    <div class=\"kpi\"><div class=\"label\">Leitor falhas</div><div class=\"value\" id=\"kFalhas\">—</div></div>\n"
"    <div class=\"kpi\"><div class=\"label\">Chaves EMU</div><div class=\"value\" id=\"kEmu\">—</div></div>\n"
"  </section>\n"
"  <section class=\"grid\">\n"
"    <div class=\"card\">\n"
"      <div class=\"card-head\"><h2>Atividade ECM</h2><span class=\"pill\" id=\"chartPeriod\">últimos 5 min</span></div>\n"
"      <canvas id=\"chart\" height=\"170\"></canvas>\n"
"    </div>\n"
"    <div class=\"card\">\n"
"      <div class=\"card-head\"><h2>Servidor</h2></div>\n"
"      <div class=\"kv\" id=\"serverInfo\"><div class=\"k\">Porta CCcam</div><div class=\"v\">—</div><div class=\"k\">Porta Newcamd</div><div class=\"v\">—</div><div class=\"k\">Limite de hops</div><div class=\"v\">—</div><div class=\"k\">Porta do painel</div><div class=\"v\">—</div><div class=\"k\">Versão</div><div class=\"v\">—</div></div>\n"
"    </div>\n"
"  </section>\n"
"  <section class=\"card\" style=\"margin-bottom:20px;\">\n"
"    <div class=\"card-head\"><h2>Clientes ligados</h2><span class=\"pill\" id=\"pillClients\">0</span></div>\n"
"    <table><thead><tr><th>Utilizador</th><th>IP</th><th>Protocolo</th><th>Ligado há</th><th>ECMs</th><th></th></tr></thead>\n"
"    <tbody id=\"clientsBody\"><tr><td colspan=\"6\" class=\"empty\">Sem clientes ligados</td></tr></tbody></table>\n"
"  </section>\n"
"  <section class=\"grid\">\n"
"    <div class=\"card\">\n"
"      <div class=\"card-head\"><h2>Leitores</h2><span class=\"pill\" id=\"pillReaders\">0</span></div>\n"
"      <table><thead><tr><th>Nome</th><th>Tipo</th><th>Estado</th><th>CAID</th><th>Hop</th><th>Prior.</th><th>ECMs</th></tr></thead>\n"
"      <tbody id=\"readersBody\"><tr><td colspan=\"7\" class=\"empty\">Sem leitores</td></tr></tbody></table>\n"
"    </div>\n"
"    <div class=\"card\">\n"
"      <div class=\"card-head\"><h2>Chaves EMU</h2><span class=\"pill\" id=\"pillEmu\">0</span></div>\n"
"      <div class=\"bars\" id=\"emuBars\"></div>\n"
"    </div>\n"
"  </section>\n"
"</main>\n"
"<footer>CCcam3 · v<span id=\"verFooter\">—</span> · GPLv3</footer>\n"
"<div id=\"toast\"></div>\n"
"<script>\n"
"const H = []; let paused = false, lastTotal = 0;\n"
"const $ = id => document.getElementById(id);\n"
"async function api(path, method) {\n"
"  try { const r = await fetch(path, { method: method || 'GET' }); return await r.json(); } catch { return null; }\n"
"}\n"
"function toast(msg, ok) {\n"
"  const t = $('toast'); t.textContent = msg; t.className = ok ? 'show ok' : 'show err';\n"
"  setTimeout(() => t.className = '', 2500);\n"
"}\n"
"function fmtAgo(ts) {\n"
"  const s = Math.max(0, Math.floor(Date.now()/1000 - ts));\n"
"  if (s < 60) return s + 's';\n"
"  if (s < 3600) return Math.floor(s/60) + 'm';\n"
"  return Math.floor(s/3600) + 'h';\n"
"}\n"
"function fmtUptime(up) {\n"
"  if (!up) return '';\n"
"  const m = Math.floor(up/60), h = Math.floor(m/60), d = Math.floor(h/24);\n"
"  if (d) return d + 'd ' + (h%24) + 'h';\n"
"  if (h) return h + 'h ' + (m%60) + 'm';\n"
"  return m + 'm';\n"
"}\n"
"function drawChart() {\n"
"  const cv = $('chart'); if (!cv || H.length < 2) return;\n"
"  const ctx = cv.getContext('2d');\n"
"  const W = cv.width = cv.offsetWidth, h = cv.height = 170;\n"
"  const max = Math.max(10, ...H);\n"
"  ctx.clearRect(0, 0, W, h);\n"
"  const g = ctx.createLinearGradient(0, 0, 0, h);\n"
"  g.addColorStop(0, 'rgba(79,140,255,0.25)'); g.addColorStop(1, 'rgba(79,140,255,0)');\n"
"  ctx.beginPath();\n"
"  H.forEach((v, i) => {\n"
"    const x = (i/(H.length-1)) * W, y = h - 12 - (v/max) * (h - 34);\n"
"    i ? ctx.lineTo(x, y) : ctx.moveTo(x, y);\n"
"  });\n"
"  ctx.strokeStyle = '#4f8cff'; ctx.lineWidth = 2; ctx.lineJoin = 'round'; ctx.stroke();\n"
"  ctx.lineTo(W, h); ctx.lineTo(0, h); ctx.closePath(); ctx.fillStyle = g; ctx.fill();\n"
"}\n"
"async function refresh() {\n"
"  const [status, ecm, cache, clients, readers, emu] = await Promise.all([\n"
"    api('/status'), api('/stats/ecm'), api('/stats/cache'), api('/clients'), api('/readers'), api('/emu/keys')\n"
"  ]);\n"
"  if (status && status.server) {\n"
"    $('dot').className = 'dot on'; $('statusText').textContent = 'online';\n"
"    $('uptime').textContent = 'up ' + fmtUptime(status.server.uptime);\n"
"    $('verFooter').textContent = status.server.version || '—';\n"
"    $('kClients').textContent = status.server.clients || 0;\n"
"    const info = [\n"
"      ['Porta CCcam', status.server.port], ['Porta Newcamd', status.server.newcamd_port || '—'],\n"
"      ['Limite de hops', status.server.hop_limit], ['Porta do painel', status.server.rest_port],\n"
"      ['Versão', status.server.version]\n"
"    ];\n"
"    $('serverInfo').innerHTML = info.map(([k,v]) => `<div class=\"k\">${k}</div><div class=\"v\">${v}</div>`).join('');\n"
"  }\n"
"  if (cache && cache.cache) {\n"
"    $('kCache').textContent = cache.cache.entries || 0;\n"
"    const r = cache.cache.hit_ratio || 0;\n"
"    const el = $('kRatio'); el.textContent = r.toFixed(1) + '%';\n"
"    el.className = 'value ' + (r > 70 ? 'ok' : r > 40 ? 'warn' : 'bad');\n"
"  }\n"
"  if (ecm && ecm.ecm) {\n"
"    const total = ecm.ecm.total_requests || 0;\n"
"    const rate = lastTotal ? Math.max(0, total - lastTotal) : 0;\n"
"    lastTotal = total;\n"
"    H.push(rate); if (H.length > 60) H.shift();\n"
"    drawChart();\n"
"    $('kEcmRate').textContent = rate;\n"
"    $('kSucesso').textContent = ecm.ecm.reader_success || 0;\n"
"    $('kFalhas').textContent = ecm.ecm.reader_fail || 0;\n"
"    $('kFalhas').className = 'value' + (ecm.ecm.reader_fail ? ' bad' : '');\n"
"  }\n"
"  if (clients && clients.clients) {\n"
"    const list = clients.clients.list || [];\n"
"    $('pillClients').textContent = list.length;\n"
"    if (!list.length) { $('clientsBody').innerHTML = '<tr><td colspan=\"6\" class=\"empty\">Sem clientes ligados</td></tr>'; }\n"
"    else $('clientsBody').innerHTML = list.map(c =>\n"
"      `<tr><td>${c.user || '—'}</td><td>${c.ip}</td><td>${c.newcamd ? 'Newcamd' : 'CCcam'}</td><td>${fmtAgo(c.connected_at)}</td><td>${c.ecm_total || 0}</td><td><button class=\"kick\" data-id=\"${c.id}\">Expulsar</button></td></tr>`\n"
"    ).join('');\n"
"  }\n"
"  if (readers && readers.readers_list) {\n"
"    const list = readers.readers_list.list || [];\n"
"    $('pillReaders').textContent = list.length;\n"
"    if (!list.length) { $('readersBody').innerHTML = '<tr><td colspan=\"7\" class=\"empty\">Sem leitores configurados</td></tr>'; }\n"
"    else {\n"
"      const types = ['Local', 'Remoto', 'Emulação'];\n"
"      $('readersBody').innerHTML = list.map(r => {\n"
"        const state = r.state === 1 ? '<span class=\"badge ok\">OK</span>' : (r.state === 0 ? '<span class=\"badge idle\">Desligado</span>' : '<span class=\"badge err\">Erro</span>');\n"
"        return `<tr><td>${r.name}</td><td>${types[r.type] || '—'}</td><td>${state}</td><td>${(r.caid||0).toString(16).toUpperCase().padStart(4,'0')}</td><td>${r.hop}</td><td>${r.priority}</td><td>${r.ecm_requests || 0}</td></tr>`;\n"
"      }).join('');\n"
"    }\n"
"  }\n"
"  if (emu && emu.emu) {\n"
"    $('kEmu').textContent = emu.emu.total || 0;\n"
"    $('pillEmu').textContent = emu.emu.total || 0;\n"
"    const bars = [['BISS', emu.emu.biss], ['Viaccess', emu.emu.viaccess], ['Cryptoworks', emu.emu.cryptoworks],\n"
"      ['PowerVU', emu.emu.powervu], ['Nagra', emu.emu.nagra], ['Irdeto', emu.emu.irdeto]];\n"
"    const max = Math.max(1, ...bars.map(b => b[1]));\n"
"    $('emuBars').innerHTML = bars.map(([l, n]) =>\n"
"      `<div class=\"bar-row\"><span class=\"l\">${l}</span><div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:${(n/max)*100}%\"></div></div><span class=\"n\">${n || 0}</span></div>`\n"
"    ).join('');\n"
"  }\n"
"  $('lastUpdate').textContent = new Date().toLocaleTimeString('pt-PT');\n"
"}\n"
"document.addEventListener('click', async e => {\n"
"  if (e.target.classList.contains('kick')) {\n"
"    const id = e.target.dataset.id;\n"
"    if (!confirm('Expulsar o cliente ' + id + '?')) return;\n"
"    const r = await api('/clients/kick?id=' + id);\n"
"    toast(r && r.kick ? 'Cliente expulso' : 'Não foi possível expulsar', r && r.kick);\n"
"    refresh();\n"
"  }\n"
"});\n"
"$('btnRefresh').onclick = refresh;\n"
"$('btnKeys').onclick = async () => {\n"
"  const r = await api('/reload/keys');\n"
"  toast(r && r.result === 'ok' ? 'Chaves recarregadas' : 'Falha ao recarregar chaves', r && r.result === 'ok');\n"
"  refresh();\n"
"};\n"
"$('btnPause').onclick = () => {\n"
"  paused = !paused;\n"
"  $('btnPause').textContent = paused ? '▶ Retomar' : '⏸ Pausar';\n"
"  $('btnPause').classList.toggle('paused', paused);\n"
"};\n"
"refresh(); setInterval(() => { if (!paused) refresh(); }, 5000);\n"
"</script>\n"
"</body>\n"
"</html>";

// --- Função para servir a página web ---
void cccam_web_interface_serve(int client_fd) {
    const char *header_fmt =
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Access-Control-Allow-Origin: *\r\n"
        "Content-Length: %zu\r\n"
        "\r\n";

    size_t body_len = strlen(WEB_PAGE_HTML);
    int needed = snprintf(NULL, 0, header_fmt, body_len) + 1;
    needed += (int)body_len;

    char *response = malloc((size_t)needed);
    if (!response) {
        close(client_fd);
        return;
    }

    int written = snprintf(response, (size_t)needed, header_fmt, body_len);
    if (written > 0) {
        memcpy(response + written, WEB_PAGE_HTML, body_len + 1);
    }

    // Envia tudo (trata escritas parciais)
    size_t total = strlen(response);
    size_t sent = 0;
    while (sent < total) {
        ssize_t n = write(client_fd, response + sent, total - sent);
        if (n <= 0) {
            if (n < 0 && errno == EINTR) continue;
            break;
        }
        sent += (size_t)n;
    }

    free(response);
    close(client_fd);
}
