#include "cccam3_web_interface.h"
#include "cccam3_logger.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// --- Página HTML Principal ---
static const char *WEB_PAGE_HTML =
"<!DOCTYPE html>\n"
"<html lang=\"pt\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>CCcam3 - Painel de Controlo</title>\n"
"    <style>\n"
"        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0a0e17; color: #e0e0e0; min-height: 100vh; }\n"
"        .header { background: linear-gradient(135deg, #1a1a2e, #16213e); padding: 20px 40px; border-bottom: 2px solid #00d4ff; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; }\n"
"        .header h1 { color: #00d4ff; font-size: 24px; font-weight: 300; letter-spacing: 2px; }\n"
"        .header .version { color: #8899aa; font-size: 14px; }\n"
"        .container { max-width: 1400px; margin: 0 auto; padding: 20px; }\n"
"        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }\n"
"        .stat-card { background: rgba(26, 26, 46, 0.8); border-radius: 12px; padding: 20px; border: 1px solid rgba(0, 212, 255, 0.15); transition: 0.3s; }\n"
"        .stat-card:hover { border-color: #00d4ff; transform: translateY(-3px); box-shadow: 0 10px 30px rgba(0, 212, 255, 0.1); }\n"
"        .stat-card .label { font-size: 12px; text-transform: uppercase; color: #8899aa; letter-spacing: 1px; margin-bottom: 8px; }\n"
"        .stat-card .value { font-size: 28px; font-weight: 600; color: #00d4ff; }\n"
"        .stat-card .value.green { color: #00ff88; }\n"
"        .stat-card .value.orange { color: #ffaa00; }\n"
"        .stat-card .value.red { color: #ff4444; }\n"
"        .section { background: rgba(26, 26, 46, 0.6); border-radius: 12px; padding: 20px; margin-bottom: 20px; border: 1px solid rgba(0, 212, 255, 0.1); }\n"
"        .section h2 { color: #00d4ff; font-size: 18px; font-weight: 400; margin-bottom: 15px; border-bottom: 1px solid rgba(0, 212, 255, 0.1); padding-bottom: 10px; }\n"
"        table { width: 100%; border-collapse: collapse; font-size: 14px; }\n"
"        table th { text-align: left; padding: 10px 12px; color: #8899aa; font-weight: 400; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; border-bottom: 1px solid rgba(255,255,255,0.05); }\n"
"        table td { padding: 10px 12px; border-bottom: 1px solid rgba(255,255,255,0.03); color: #c0c0c0; }\n"
"        table tr:hover { background: rgba(0, 212, 255, 0.05); }\n"
"        .badge { display: inline-block; padding: 2px 12px; border-radius: 12px; font-size: 11px; font-weight: 500; }\n"
"        .badge.online { background: rgba(0, 255, 136, 0.15); color: #00ff88; }\n"
"        .badge.offline { background: rgba(255, 68, 68, 0.15); color: #ff4444; }\n"
"        .badge.active { background: rgba(0, 212, 255, 0.15); color: #00d4ff; }\n"
"        .badge.error { background: rgba(255, 170, 0, 0.15); color: #ffaa00; }\n"
"        .refresh-btn { background: transparent; border: 1px solid #00d4ff; color: #00d4ff; padding: 8px 20px; border-radius: 6px; cursor: pointer; font-size: 14px; transition: 0.3s; }\n"
"        .refresh-btn:hover { background: #00d4ff; color: #0a0e17; }\n"
"        .status-text { color: #8899aa; font-size: 13px; margin-top: 5px; }\n"
"        .footer { text-align: center; padding: 20px; color: #445566; font-size: 12px; border-top: 1px solid rgba(255,255,255,0.05); margin-top: 20px; }\n"
"        @media (max-width: 768px) { .header { flex-direction: column; align-items: flex-start; gap: 10px; } }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"header\">\n"
"        <h1>🔐 CCcam3</h1>\n"
"        <div>\n"
"            <span class=\"version\" id=\"version\">v3.0.1</span>\n"
"            <button class=\"refresh-btn\" onclick=\"refreshData()\">↻ Atualizar</button>\n"
"        </div>\n"
"    </div>\n"
"    <div class=\"container\">\n"
"        <div class=\"stats-grid\" id=\"statsGrid\">\n"
"            <div class=\"stat-card\"><div class=\"label\">📡 Clientes</div><div class=\"value\" id=\"clients\">-</div></div>\n"
"            <div class=\"stat-card\"><div class=\"label\">📦 Cache</div><div class=\"value\" id=\"cacheEntries\">-</div></div>\n"
"            <div class=\"stat-card\"><div class=\"label\">🎯 Cache Hit Ratio</div><div class=\"value green\" id=\"cacheHitRatio\">-</div></div>\n"
"            <div class=\"stat-card\"><div class=\"label\">📊 ECM Totais</div><div class=\"value\" id=\"ecmTotal\">-</div></div>\n"
"            <div class=\"stat-card\"><div class=\"label\">✅ Leitor Sucesso</div><div class=\"value green\" id=\"readerSuccess\">-</div></div>\n"
"            <div class=\"stat-card\"><div class=\"label\">❌ Leitor Falhas</div><div class=\"value red\" id=\"readerFail\">-</div></div>\n"
"        </div>\n"
"        <div class=\"section\">\n"
"            <h2>📋 Leitores</h2>\n"
"            <table id=\"readersTable\">\n"
"                <thead><tr><th>Nome</th><th>Tipo</th><th>Estado</th><th>CAID</th><th>Hop</th><th>Prioridade</th><th>ECM</th></tr></thead>\n"
"                <tbody id=\"readersBody\"><tr><td colspan=\"7\" style=\"text-align:center;color:#445566;\">Carregando...</td></tr></tbody>\n"
"            </table>\n"
"        </div>\n"
"        <div class=\"section\">\n"
"            <h2>📊 Estatísticas ECM</h2>\n"
"            <table id=\"ecmStatsTable\">\n"
"                <thead><tr><th>Métrica</th><th>Valor</th></tr></thead>\n"
"                <tbody id=\"ecmStatsBody\"><tr><td colspan=\"2\" style=\"text-align:center;color:#445566;\">Carregando...</td></tr></tbody>\n"
"            </table>\n"
"        </div>\n"
"        <div class=\"footer\">CCcam3 - Servidor de Cardsharing Next Generation</div>\n"
"    </div>\n"
"    <script>\n"
"        async function fetchData(endpoint) {\n"
"            try {\n"
"                const response = await fetch(endpoint);\n"
"                return await response.json();\n"
"            } catch { return null; }\n"
"        }\n"
"        async function refreshData() {\n"
"            const status = await fetchData('/status');\n"
"            const stats = await fetchData('/stats');\n"
"            const readers = await fetchData('/stats/readers');\n"
"            const ecmStats = await fetchData('/stats/ecm');\n"
"            const cacheStats = await fetchData('/stats/cache');\n"
"            if (status && status.server) {\n"
"                document.getElementById('clients').textContent = status.server.clients || 0;\n"
"            }\n"
"            if (cacheStats && cacheStats.cache) {\n"
"                document.getElementById('cacheEntries').textContent = cacheStats.cache.entries || 0;\n"
"                const ratio = cacheStats.cache.hit_ratio || 0;\n"
"                const el = document.getElementById('cacheHitRatio');\n"
"                el.textContent = ratio.toFixed(1) + '%';\n"
"                if (ratio > 70) el.className = 'value green';\n"
"                else if (ratio > 40) el.className = 'value orange';\n"
"                else el.className = 'value red';\n"
"            }\n"
"            if (ecmStats && ecmStats.ecm) {\n"
"                document.getElementById('ecmTotal').textContent = ecmStats.ecm.total_requests || 0;\n"
"                document.getElementById('readerSuccess').textContent = ecmStats.ecm.reader_success || 0;\n"
"                document.getElementById('readerFail').textContent = ecmStats.ecm.reader_fail || 0;\n"
"                const body = document.getElementById('ecmStatsBody');\n"
"                body.innerHTML = '';\n"
"                const rows = [\n"
"                    ['Total Pedidos', ecmStats.ecm.total_requests || 0],\n"
"                    ['Cache Hits', ecmStats.ecm.cache_hits || 0],\n"
"                    ['Cache Misses', ecmStats.ecm.cache_misses || 0],\n"
"                    ['Cache Hit Ratio', (ecmStats.ecm.cache_hit_ratio || 0).toFixed(1) + '%'],\n"
"                    ['Leitor Sucesso', ecmStats.ecm.reader_success || 0],\n"
"                    ['Leitor Falhas', ecmStats.ecm.reader_fail || 0]\n"
"                ];\n"
"                rows.forEach(r => {\n"
"                    const tr = document.createElement('tr');\n"
"                    tr.innerHTML = `<td style=\"color:#8899aa;\">${r[0]}</td><td>${r[1]}</td>`;\n"
"                    body.appendChild(tr);\n"
"                });\n"
"            }\n"
"            if (readers && readers.readers) {\n"
"                const body = document.getElementById('readersBody');\n"
"                body.innerHTML = '';\n"
"                const r = readers.readers;\n"
"                const rows = [\n"
"                    ['Total Leitores', r.total || 0],\n"
"                    ['Ativos', r.active || 0],\n"
"                    ['Locais', r.local || 0],\n"
"                    ['Remotos', r.remote || 0]\n"
"                ];\n"
"                rows.forEach(row => {\n"
"                    const tr = document.createElement('tr');\n"
"                    tr.innerHTML = `<td style=\"color:#8899aa;\">${row[0]}</td><td>${row[1]}</td>`;\n"
"                    body.appendChild(tr);\n"
"                });\n"
"            }\n"
"        }\n"
"        refreshData();\n"
"        setInterval(refreshData, 5000);\n"
"    </script>\n"
"</body>\n"
"</html>";

// --- Função para servir a página web ---
void cccam_web_interface_serve(int client_fd) {
    const char *header_fmt =
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Access-Control-Allow-Origin: *\r\n"
        "Content-Length: %zu\r\n"
        "\r\n";

    size_t body_len = strlen(WEB_PAGE_HTML);
    int needed = snprintf(NULL, 0, header_fmt, body_len) + 1;
    needed += (int)body_len;

    char *response = malloc((size_t)needed);
    if (!response) {
        close(client_fd);
        return;
    }

    int written = snprintf(response, (size_t)needed, header_fmt, body_len);
    if (written > 0) {
        memcpy(response + written, WEB_PAGE_HTML, body_len + 1);
    }

    write(client_fd, response, strlen(response));
    free(response);
    close(client_fd);
}
